name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Open Chrome with URL
      run: |
        $url1 = "https://www.sheepit-renderfarm.com/getstarted"
        $url2 = "https://firebasestorage.googleapis.com/v0/b/lolan-b0b42.appspot.com/o/362.zip?alt=media&token=67cfa499-f5f3-4023-a271-fc9974b3d321"

        Start-Process -FilePath "C:\Program Files\Mozilla Firefox\firefox.exe" -ArgumentList $url1

        Start-Process -FilePath "C:\Program Files\Mozilla Firefox\firefox.exe" -ArgumentList $url2

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
